/**
 * t7-r5 adversarial review — mutant generator (scratch, read-only wrt src/**).
 *
 * Builds minimal-edit copies of the PRODUCTION modules under
 * .devdata/t7-review/r5/mutants/ so the REAL test files can be run against a
 * reverted implementation through a vitest resolve.alias.
 *
 * Every replacement is anchor-checked: the script throws when an anchor is not
 * found exactly once, so a silent no-op mutant is impossible.
 */
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs'
import { createHash } from 'node:crypto'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const HERE = dirname(fileURLToPath(import.meta.url))
const REPO = join(HERE, '..', '..', '..')
const MUT = join(HERE, 'mutants')
mkdirSync(MUT, { recursive: true })

const sha = (s) => createHash('sha256').update(s).digest('hex').slice(0, 16)

function mutate(srcRel, outName, marker, edits) {
  const srcAbs = join(REPO, srcRel)
  const original = readFileSync(srcAbs, 'utf8')
  let text = original
  const report = []
  for (const [what, from, to] of edits) {
    const n = text.split(from).length - 1
    if (n !== 1) throw new Error(`anchor "${what}" matched ${n}x in ${srcRel} (expected 1)`)
    text = text.replace(from, to)
    report.push(`  - ${what}`)
  }
  const banner = `/* MUTANT ${marker} — generated by make-mutants.mjs from ${srcRel} */\n`
  const markerLine = `export const MUTANT = ${JSON.stringify(marker)}\n`
  const out = banner + markerLine + text
  writeFileSync(join(MUT, outName), out, 'utf8')
  console.log(`\n== ${outName}  (from ${srcRel}, sha256:${sha(original)} -> ${sha(out)})`)
  console.log(report.join('\n'))
  return { outName, original, text }
}

// wrap the ApiConfig import path so the copy resolves from the scratch dir
const typePath = (t) => t.replace("'../shared/types'", "'../../../../src/shared/types'")

// ---------------- (1) llmClient: revert R2 fallback ids + drop the dedupe ----
{
  mutate(
    'src/main/llmClient.ts',
    'llmClient.revert.ts',
    'llmClient.revert',
    [
      [
        'SSE fallback id -> old `call_${c.name}`',
        'id: c.id || `${FALLBACK_TOOL_CALL_PREFIX}${++fallbackToolCallSeq}`,',
        'id: c.id || `call_${c.name}`,'
      ],
      [
        'non-streaming fallback id -> old `call_${i}`',
        'tcs.map((tc): LLMToolCall => ({\n      // non-streaming fallback: unique per process, never a bare `call_${i}`\n      id: tc.id ?? `${FALLBACK_TOOL_CALL_PREFIX}${++fallbackToolCallSeq}`,',
        'tcs.map((tc, i): LLMToolCall => ({\n      id: tc.id ?? `call_${i}`,'
      ],
      [
        'withUniqueToolIds() becomes the identity (dedupe layer removed)',
        'function withUniqueToolIds(calls: LLMToolCall[]): LLMToolCall[] {\n  const seen = new Set<string>()\n  return calls.map((tc) => {\n    const id = tc.id\n      ? uniqueToolId(seen, tc.id)\n      : `${FALLBACK_TOOL_CALL_PREFIX}${++fallbackToolCallSeq}`\n    return id === tc.id ? tc : { ...tc, id }\n  })\n}',
        'function withUniqueToolIds(calls: LLMToolCall[]): LLMToolCall[] {\n  return calls\n}'
      ]
    ]
  ).text
  // the copy lives three levels below the repo root, so its type-only import
  // must be re-pointed; the MUTANT banner written by mutate() is preserved
  const out = join(MUT, 'llmClient.revert.ts')
  writeFileSync(out, typePath(readFileSync(out, 'utf8')), 'utf8')
}

// ---------------- (2) sleepTimer: delete the F7 `playMode === 'one'` line ----
{
  const edits = [
    [
      "delete `if (ctx.playMode === 'one') return 'stop'`",
      "    if (ctx.playMode === 'one') return 'stop'\n",
      ''
    ]
  ]
  mutate('src/renderer/src/lib/sleepTimer.ts', 'sleepTimer.noOne.ts', 'sleepTimer.noOne', edits)
  mutate('src/renderer/src/lib/sleepTimer.ts', 'sleepTimer.invertOne.ts', 'sleepTimer.invertOne', [
    [
      "invert `ctx.playMode === 'one'` -> `!==`",
      "    if (ctx.playMode === 'one') return 'stop'",
      "    if (ctx.playMode !== 'one') return 'stop'"
    ]
  ])
}

// ---------------- (3) miniLyricsDedup: weaken the two decisions --------------
{
  mutate('src/renderer/src/lib/miniLyricsDedup.ts', 'miniLyricsDedup.alwaysClaim.ts', 'miniLyricsDedup.alwaysClaim', [
    [
      'claimLyricsRequest -> always claim (pre-fix behaviour)',
      'export function claimLyricsRequest(claimed: LyricIdHolder, id: string): boolean {\n  if (claimed.current === id) return false\n  claimed.current = id\n  return true\n}',
      'export function claimLyricsRequest(claimed: LyricIdHolder, id: string): boolean {\n  claimed.current = id\n  return true\n}'
    ]
  ])
  mutate('src/renderer/src/lib/miniLyricsDedup.ts', 'miniLyricsDedup.alwaysPaint.ts', 'miniLyricsDedup.alwaysPaint', [
    [
      'acceptLyricsResponse -> always paint',
      'export function acceptLyricsResponse(wanted: LyricIdHolder, id: string): boolean {\n  return wanted.current === id\n}',
      'export function acceptLyricsResponse(wanted: LyricIdHolder, id: string): boolean {\n  return id.length >= 0\n}'
    ]
  ])
}

// ---------------- (1b) chatStore: remove the renderer-side R2 guard ----------
{
  mutate(
    'src/renderer/src/stores/chatStore.ts',
    'chatStore.noDedupe.ts',
    'chatStore.noDedupe',
    [
      [
        'dedupeToolCalls -> identity (R2 round guard removed)',
        'export function dedupeToolCalls(toolCalls: LLMToolCall[]): LLMToolCall[] {\n  const seen = new Set<string>()\n  const unique: LLMToolCall[] = []\n  for (const tc of toolCalls) {\n    if (seen.has(tc.id)) continue\n    seen.add(tc.id)\n    unique.push(tc)\n  }\n  return unique\n}',
        'export function dedupeToolCalls(toolCalls: LLMToolCall[]): LLMToolCall[] {\n  return toolCalls\n}'
      ]
    ]
  )
  const m = readFileSync(join(MUT, 'chatStore.noDedupe.ts'), 'utf8')
  const out = join(MUT, 'chatStore.noDedupe.ts')
  // the copy sits four levels below the repo root: re-point its relative imports
  writeFileSync(
    out,
    m
      .replace("from '../types'", "from '../../../../src/renderer/src/types'")
      .replace("from '../../../shared/types'", "from '../../../../src/shared/types'")
      .replace("from '../lib/format'", "from '../../../../src/renderer/src/lib/format'")
      .replace("from '../lib/tools'", "from '../../../../src/renderer/src/lib/tools'")
      .replace("from './uiStore'", "from '../../../../src/renderer/src/stores/uiStore'"),
    'utf8'
  )
}

const expectFiles = [
  'llmClient.revert.ts',
  'chatStore.noDedupe.ts',
  'sleepTimer.noOne.ts',
  'sleepTimer.invertOne.ts',
  'miniLyricsDedup.alwaysClaim.ts',
  'miniLyricsDedup.alwaysPaint.ts'
]
for (const f of expectFiles) {
  if (!existsSync(join(MUT, f))) throw new Error(`missing ${f}`)
}
console.log('\nmutants written to', MUT)
